### ISSUE TITLE
Battrie voltage measurement

### ISSUE THREAD

**Issue by hjoertel** [aqua-scope/lorain#1]
Batterie Voltage seems not to work.
I added serail print to see  what the analog(Read) delivers:
`voltage = analogRead(PIN_VOLTAGE);  // 4095 == 3,3V

Serial.printf("Voltage %d\n", voltage);

voltage = voltage/10*75/100;

Serial.printf("Voltage %d\n", voltage);`

After start up the result is:
  Voltage 72
  Voltage 5
and "5" is the value seen in the LoRa message, what is a strange value.
After 15 minutes, the batterie voltage is measured again :
  Voltage 81
  Voltage 6
after that, the following measures are all the same.

**Comment by christianpaetz** [comment]
thanks for debugging. Do you run it on battery while connected to USB/UART or do you use the UART power?

**Comment by hjoertel** [comment]
Am Freitag, 14. Oktober 2022, 18:04:45 CEST schrieb christianpaetz:
> thanks for debugging. Do you run it on battery while connected to USB/UART or do you use the UART power?


Can that be the reason? I can only debug when the module is connected vie the USB->TTL powered with 3,3 V and outside of the Rain housing.

Now, with running in the housing, from the TTN console I get

"decoded_payload": {
        "bat_consumption": 0,
        "bat_voltage": 32,
        "capabilities": 1,
        "fw_version": 221014,
        "hw_version": 5,
        "rainlevel": 1,
        "temperature": 220,
        "uptime": 0
      },

Does that mean the value is correct and "32" means 3,2 V ?


Heinz

**Comment by christianpaetz** [comment]
yes, accd. to manual value is in 100 mV steps, hence the 32 is correct. Please note that the board as an additional power converter and battery is measured before the converter while the UART is connected after the converter
