### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by michael-gollan** [aqua-scope/lorain#3]
Hi,

We might utilize the sensor in a citizen science project. However, it is required for this purpose that it is open source and has a license.

Could you please add an open source license (e.g., GPL or EUPL 1.2 https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/2020-03/EUPL-1.2%20EN.txt) file to the root directory?

Best regards

**Comment by aqua-scope** [comment]
done
